package com.btireland.talos.mygroup.myproject.repository;

import com.btireland.talos.mygroup.myproject.domain.ExampleOrder;

//@JaversSpringDataAuditable
public interface ExampleOrderRepository extends JpaRsqlRepository<ExampleOrder, Long> {

    /**
     * Standard query method. The implementation will be generated by Spring.
     * Have a look here for further info https://docs.spring.io/spring-data/jpa/docs/current/reference/html/#repositories
     *
     * @param externalReference external reference of the order
     * @return The {@link ExampleOrder} matching externalReference or null if not found
     */
    ExampleOrder findByExternalReference(String externalReference);
}
